import { mkdirSync, writeFileSync, copyFileSync } from 'node:fs';
const origin='https://timefusionsidk.com';
const tools=[
 ['audiolift','AudioLift','Audio & video','Extract the audio. Keep the moment.','Turn a video into an audio file. Choose formats including MP3, WAV and M4A, then save the result.','↗','blue'],
 ['clipturn','ClipTurn','Video editing','Make the cut you had in mind.','Trim, reverse, rotate and crop your video with simple controls, right in your browser.','↔','purple'],
 ['clearcut','ClearCut','Image editing','Your subject. Without the background.','Remove an image background and download a transparent PNG for your next design.','◐','pink'],
 ['tempo','Tempo','Time & focus','A little more focus. A lot less fuss.','Set a countdown for your next task or measure elapsed time with a stopwatch.','◷','orange'],
 ['bodymetric','BodyMetric','Everyday calculations','Understand your BMI, simply.','Calculate BMI from height and weight, with explanations and the limitations of the result.','＋','green']
];
const footer=`<footer><a class="brand" href="/">timefusions<span> </span></a><p>Small tools. More possibilities.</p><nav aria-label="Footer"><a href="/about">About</a><a href="/contact">Contact</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a><button type="button" id="privacy-choice">Cookie preferences</button></nav><small>© ${new Date().getFullYear()} Timefusions</small></footer>`;
const home=`<section class="hero"><div><p class="eyebrow">YOUR EVERYDAY DIGITAL TOOLBOX</p><h1>Small tasks.<br><span>Sorted.</span></h1><p class="intro">Five useful tools for the things you do every day. Edit a clip, clean up an image, find your focus — and get on with it.</p><a class="primary" href="#tools">Find your tool <span aria-hidden="true">↓</span></a><p class="note">Free to use <span>·</span> No account needed</p></div><div class="hero-panel" aria-label="Five tools in one collection"><p>LESS SETUP. MORE DOING.</p><div class="tool-stack">${tools.map(([id,name,cat,,,icon,color])=>`<a href="https://${id}.timefusionsidk.com" class="stack-row"><span class="icon ${color}" aria-hidden="true">${icon}</span><span><strong>${name}</strong><small>${cat}</small></span><span class="stack-arrow" aria-hidden="true">↗</span></a>`).join('')}</div><p class="panel-foot">ONE COLLECTION. FIVE POSSIBILITIES.</p></div></section><section class="directory" id="tools"><div class="section-heading"><div><p class="eyebrow">THE COLLECTION</p><h2>What are we making easier?</h2></div><p>Pick a tool. Get straight to work.</p></div><div class="cards">${tools.map(([id,name,cat,heading,desc,icon,color],i)=>`<article class="card ${i===0?'featured':''}"><div class="card-top"><span class="icon ${color}" aria-hidden="true">${icon}</span><span class="category">${cat}</span></div><h3>${name}</h3><h4>${heading}</h4><p>${desc}</p><a href="https://${id}.timefusionsidk.com" class="tool-link">Open ${name}<span aria-hidden="true">↗</span></a></article>`).join('')}<article class="collection-note"><span aria-hidden="true">✳</span><h3>Useful by design.</h3><p>No accounts to create. No complicated setup. Just a direct route to the task in front of you.</p><a href="/about">Meet Timefusions →</a></article></div></section><section class="principles"><div><p class="eyebrow">A SIMPLER WAY TO WORK</p><h2>Less friction.<br>More flow.</h2></div><div><h3>Start with what you need</h3><p>Each tool has one clear purpose, with controls that help you get there quickly.</p><h3>Your files stay in your browser</h3><p>Our media tools process selected files on your device. Large files and AI models can take more time or memory, especially on phones.</p><h3>Help is a message away</h3><p>Found a problem or have an idea? <a href="mailto:timefusions.idk@gmail.com">Tell us about it.</a></p></div></section>`;
const pages={
 '': ['Free browser tools for everyday tasks', 'Explore AudioLift, ClipTurn, ClearCut, Tempo and BodyMetric. Free browser tools for media editing, timing and everyday calculations.',home],
 about:['About Timefusions','Meet the collection of free tools built to make everyday digital tasks easier.',`<p class="eyebrow">ABOUT TIMEFUSIONS</p><h1>A useful little<br>corner of the web.</h1><p class="lead">Timefusions brings independent browser tools together in one easy-to-find collection.</p><h2>Made for everyday tasks</h2><p>Sometimes you only need the audio from a video, a cleaner image, or a timer to keep a task moving. Our tools focus on those small jobs, with no account required.</p><h2>Five tools, one collection</h2><p>AudioLift extracts audio from video. ClipTurn handles simple video edits. ClearCut removes image backgrounds. Tempo gives you timers and a stopwatch. BodyMetric helps explain a BMI calculation.</p><h2>Built with practical limits in mind</h2><p>Media processing happens in your browser. Performance depends on your device, browser and file size. Keep your original files, and use a desktop browser for larger jobs.</p><a class="primary" href="/#tools">Explore the tools →</a>`],
 contact:['Contact Timefusions','Contact Timefusions for support, feedback, accessibility issues or privacy questions.',`<p class="eyebrow">GET IN TOUCH</p><h1>We’re listening.</h1><p class="lead">A question, a bug, or an idea for a better tool? Send us an email.</p><a class="email" href="mailto:timefusions.idk@gmail.com">timefusions.idk@gmail.com</a><h2>Help us understand the problem</h2><p>Include the tool name, your browser and device, and what happened. A screenshot of the error can help. Please do not send private media files or personal health information.</p><h2>Privacy and accessibility</h2><p>Use the same email for questions about data, copyright concerns or anything that makes a tool difficult to use.</p>`],
 privacy:['Privacy Policy','How the Timefusions directory uses analytics, cookies and support messages.',`<p class="eyebrow">LAST UPDATED · SEPTEMBER 27, 2026</p><h1>Privacy Policy</h1><p>This policy covers the Timefusions directory at timefusionsidk.com. Each linked app has its own privacy policy describing its processing.</p><h2>Browsing this directory</h2><p>No account is required. The directory does not ask you to upload files or enter health information. Our hosting provider may process technical request information, such as an IP address and browser details, to serve and protect the website.</p><h2>Optional analytics</h2><p>We use Google Analytics only after you accept analytics on this directory. It measures page visits and general website usage and may use cookies and device information. We disable advertising personalization in our tag configuration. We do not intentionally send media files, filenames or health measurements to Analytics.</p><p>You can accept or decline analytics and change your choice using Cookie preferences in the footer. Your preference is stored in this browser. Declining does not prevent access to any tool. Withdrawing consent stops further tracking from this directory after the page reloads; it does not erase data previously collected by Google.</p><p>Learn more at <a href="https://policies.google.com/privacy">Google’s Privacy Policy</a>.</p><h2>Messages you send us</h2><p>If you email us, your email address and message are used to respond to your request. Avoid including sensitive files or health details. Contact us if you want us to delete support correspondence, subject to any necessary retention.</p><h2>Linked tools</h2><p>Each tool operates on a separate subdomain. Review its privacy notice before using it. Choices made on this directory do not control tracking on those separate apps.</p><h2>Contact</h2><p>Email <a href="mailto:timefusions.idk@gmail.com">timefusions.idk@gmail.com</a> for privacy questions.</p>`],
 terms:['Terms of Use','Terms for using the Timefusions directory and linked browser tools.',`<p class="eyebrow">LAST UPDATED · SEPTEMBER 27, 2026</p><h1>Terms of Use</h1><p>Timefusions provides this directory to help you find and use our browser tools. By using it, you agree to these terms.</p><h2>Using the tools</h2><p>Use the service lawfully and process only content you own or have permission to use. Do not interfere with the service or attempt to misuse it. Each linked app may have additional terms.</p><h2>Availability and results</h2><p>Tools are provided as available, without a guarantee of uninterrupted service or perfect results. Features may change. Keep original copies of your files and check exported results before relying on them.</p><h2>Health and timing limitations</h2><p>BodyMetric offers general educational information, not a diagnosis or medical advice. BMI does not describe every aspect of health. Tempo is not intended for safety-critical timing; browsers can pause or delay background tasks.</p><h2>Responsibility</h2><p>To the extent permitted by applicable law, Timefusions is not responsible for losses arising from use of these free tools. Nothing here excludes rights or responsibilities that cannot be excluded under applicable law.</p><h2>Contact</h2><p>Send questions to <a href="mailto:timefusions.idk@gmail.com">timefusions.idk@gmail.com</a>.</p>`],
 '404':['Page not found','This page could not be found.',`<p class="eyebrow">404 · PAGE NOT FOUND</p><h1>Let’s get you<br>back on track.</h1><p>The page you’re looking for isn’t here.</p><a class="primary" href="/">Back to the tools →</a>`]
};
mkdirSync('dist',{recursive:true});
for(const [path,[title,description,body]] of Object.entries(pages)){
 const url=origin+(path?'/'+path:'/');
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | Timefusions</title><meta name="description" content="${description}"><link rel="canonical" href="${url}">${path==='404'?'<meta name="robots" content="noindex">':''}<meta property="og:type" content="website"><meta property="og:title" content="${title} | Timefusions"><meta property="og:description" content="${description}"><meta property="og:url" content="${url}"><meta name="theme-color" content="#2348ef"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/style.css"><script src="/analytics.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a><header><a href="/" class="brand" aria-label="Timefusions home"><span class="brand-symbol" aria-hidden="true">t</span>timefusions<span> </span></a><nav aria-label="Main"><a href="/#tools">The tools</a><a href="/about">About</a><a href="/contact">Contact</a></nav></header><main id="main" class="${path?'document':''}">${body}</main>${footer}<aside id="consent" class="consent" aria-label="Analytics preference" hidden><p><strong>A little insight helps us improve.</strong><br>Allow optional analytics on this directory? <a href="/privacy">Privacy policy</a></p><div><button id="decline" type="button">Decline</button><button id="accept" type="button">Accept analytics</button></div></aside></body></html>`;
 writeFileSync('dist/'+(path||'index')+'.html',html);
}
for(const file of ['style.css','analytics.js','favicon.svg'])copyFileSync(file,'dist/'+file);
writeFileSync('dist/robots.txt',`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);
writeFileSync('dist/sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+Object.keys(pages).filter(p=>p!=='404').map(p=>`<url><loc>${origin}${p?'/'+p:'/'}</loc></url>`).join('')+'</urlset>');
console.log('Built six static pages, sitemap and robots.txt.');
